[build]
  functions = "netlify/functions"

# (optional but handy) CORS for local testing / Bolt
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[functions]
  node_bundler = "esbuild"
